package noMain;

import examinationsystem.*;
import examinationsystem.Exam;
import java.awt.Color;
import javax.swing.*;
import java.io.*;
import java.util.*;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartFrame;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.CategoryPlot;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.data.category.DefaultCategoryDataset;

public class instructor extends javax.swing.JFrame {

    /**
     * Creates new form instructor
     */
    Instructor i = new Instructor();
    Histogram Histo = new Histogram();
    ArrayList<String> IDs = new ArrayList<String>();
    String[] ids;
    Map<Integer, Integer> GradesAndStudents;

    public instructor() {
        initComponents();

    }

    public instructor(Instructor i) {
        initComponents();
        jLabel40.hide();
        jLabel42.hide();
        this.i = i;
        try {
            IDs = Histo.ExamIDsRead();
            ids = new String[IDs.size()];
            if (IDs != null) {
                for (int j = 0; j < IDs.size(); j++) {
                    ids[j] = IDs.get(j);
                }
                I_IDs_cmbo.setModel(new javax.swing.DefaultComboBoxModel(ids));
            }
        } catch (IOException e) {
            System.out.println(e);
        }
        I_name_txt.setText(i.getName());
        I_phone_txt.setText(i.getPhoneins());
        I_address_txt.setText(i.getAddressins());
        I_Email_txt.setText(i.getEmailins());
        I_Age_txt.setText(i.getAge());
        for (String Course : i.getCourses()) {
            I_subject_cmbo.addItem(Course);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        I_LogOut_btn = new javax.swing.JButton();
        jLabel27 = new javax.swing.JLabel();
        I_Hints_pnl = new javax.swing.JTabbedPane();
        I_Eval_pnl = new javax.swing.JPanel();
        jLabel26 = new javax.swing.JLabel();
        I_IDs_cmbo = new javax.swing.JComboBox();
        jPanel4 = new javax.swing.JPanel();
        jLabel40 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        I_showHisto_btn = new javax.swing.JButton();
        I_Info_pnl = new javax.swing.JPanel();
        I_GInfo_pnl = new javax.swing.JPanel();
        I_name_lbl = new javax.swing.JLabel();
        I_phone_lbl = new javax.swing.JLabel();
        I_address_lbl = new javax.swing.JLabel();
        I_email_lbl = new javax.swing.JLabel();
        I_name_txt = new javax.swing.JTextField();
        I_phone_txt = new javax.swing.JTextField();
        I_address_txt = new javax.swing.JTextField();
        I_Email_txt = new javax.swing.JTextField();
        jLabel39 = new javax.swing.JLabel();
        I_Age_txt = new javax.swing.JTextField();
        I_exam_pnl = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        I_Ques_SPane = new javax.swing.JScrollPane();
        I_Ques_pnl = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        I_Q1_txt = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        I_choise1_txt = new javax.swing.JTextField();
        I_choise2_txt = new javax.swing.JTextField();
        I_choise3_txt = new javax.swing.JTextField();
        I_choise4_txt = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        I_Q4_txt = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        I_choise41_txt = new javax.swing.JTextField();
        I_choise43_txt = new javax.swing.JTextField();
        I_choise44_txt = new javax.swing.JTextField();
        I_choise42_txt = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        I_Q3_txt = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        I_choise31_txt = new javax.swing.JTextField();
        I_choise32_txt = new javax.swing.JTextField();
        I_choise33_txt = new javax.swing.JTextField();
        I_choise34_txt = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        I_Q2_txt = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        I_choise21_txt = new javax.swing.JTextField();
        I_choise22_txt = new javax.swing.JTextField();
        I_choise23_txt = new javax.swing.JTextField();
        I_choise24_txt = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        I_correct2_cmbo = new javax.swing.JComboBox();
        jLabel36 = new javax.swing.JLabel();
        I_correct3_cmbo = new javax.swing.JComboBox();
        jLabel37 = new javax.swing.JLabel();
        I_correct1_cmbo = new javax.swing.JComboBox();
        jLabel38 = new javax.swing.JLabel();
        I_correct4_cmbo = new javax.swing.JComboBox();
        I_submit_btn = new javax.swing.JButton();
        I_subject_cmbo = new javax.swing.JComboBox();
        jLabel28 = new javax.swing.JLabel();
        I_Duration_cmbo = new javax.swing.JComboBox();
        jLabel29 = new javax.swing.JLabel();
        I_day_cmbo = new javax.swing.JComboBox();
        I_month_cmbo = new javax.swing.JComboBox();
        jLabel30 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        I_STime_txt = new javax.swing.JTextField();
        jLabel41 = new javax.swing.JLabel();
        I_ExamID_tx = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        I_LogOut_btn.setText("Logout");
        I_LogOut_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                I_LogOut_btnActionPerformed(evt);
            }
        });

        jLabel27.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel27.setText("Welcome");

        jLabel26.setText("Exam Subject: ");

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Report for (Subject)"));

        jLabel40.setText("jLabel40");

        jLabel42.setText("jLabel42");

        jLabel43.setText("Most tough question: ");

        jLabel44.setText("Second Most tough question:");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel43)
                    .addComponent(jLabel44))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel42)
                    .addComponent(jLabel40))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel43)
                    .addComponent(jLabel40))
                .addGap(54, 54, 54)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel42)
                    .addComponent(jLabel44))
                .addContainerGap(195, Short.MAX_VALUE))
        );

        I_showHisto_btn.setText("Show Histogram");
        I_showHisto_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                I_showHisto_btnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout I_Eval_pnlLayout = new javax.swing.GroupLayout(I_Eval_pnl);
        I_Eval_pnl.setLayout(I_Eval_pnlLayout);
        I_Eval_pnlLayout.setHorizontalGroup(
            I_Eval_pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(I_Eval_pnlLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(I_Eval_pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(I_Eval_pnlLayout.createSequentialGroup()
                        .addComponent(jLabel26)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(I_IDs_cmbo, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 541, Short.MAX_VALUE)
                        .addComponent(I_showHisto_btn))
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(45, 45, 45))
        );
        I_Eval_pnlLayout.setVerticalGroup(
            I_Eval_pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(I_Eval_pnlLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(I_Eval_pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel26)
                    .addComponent(I_IDs_cmbo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(I_showHisto_btn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        I_Hints_pnl.addTab("Evaluation Report", I_Eval_pnl);

        I_GInfo_pnl.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "General Info"));

        I_name_lbl.setText("Name:");

        I_phone_lbl.setText("Phone:");

        I_address_lbl.setText("Address:");

        I_email_lbl.setText("Email:");

        jLabel39.setText("Age:");

        javax.swing.GroupLayout I_GInfo_pnlLayout = new javax.swing.GroupLayout(I_GInfo_pnl);
        I_GInfo_pnl.setLayout(I_GInfo_pnlLayout);
        I_GInfo_pnlLayout.setHorizontalGroup(
            I_GInfo_pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(I_GInfo_pnlLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(I_GInfo_pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(I_GInfo_pnlLayout.createSequentialGroup()
                        .addGroup(I_GInfo_pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(I_email_lbl)
                            .addComponent(jLabel39))
                        .addGap(32, 32, 32)
                        .addGroup(I_GInfo_pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(I_Email_txt, javax.swing.GroupLayout.DEFAULT_SIZE, 438, Short.MAX_VALUE)
                            .addComponent(I_Age_txt)))
                    .addGroup(I_GInfo_pnlLayout.createSequentialGroup()
                        .addGroup(I_GInfo_pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(I_name_lbl)
                            .addComponent(I_phone_lbl)
                            .addComponent(I_address_lbl))
                        .addGap(17, 17, 17)
                        .addGroup(I_GInfo_pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(I_address_txt)
                            .addComponent(I_phone_txt)
                            .addComponent(I_name_txt))))
                .addGap(315, 315, 315))
        );
        I_GInfo_pnlLayout.setVerticalGroup(
            I_GInfo_pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(I_GInfo_pnlLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(I_GInfo_pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(I_name_lbl)
                    .addComponent(I_name_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(I_GInfo_pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(I_phone_lbl)
                    .addComponent(I_phone_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(I_GInfo_pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(I_address_lbl)
                    .addComponent(I_address_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(I_GInfo_pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(I_email_lbl)
                    .addComponent(I_Email_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(I_GInfo_pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel39)
                    .addComponent(I_Age_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(46, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout I_Info_pnlLayout = new javax.swing.GroupLayout(I_Info_pnl);
        I_Info_pnl.setLayout(I_Info_pnlLayout);
        I_Info_pnlLayout.setHorizontalGroup(
            I_Info_pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(I_Info_pnlLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(I_GInfo_pnl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        I_Info_pnlLayout.setVerticalGroup(
            I_Info_pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(I_Info_pnlLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(I_GInfo_pnl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(196, Short.MAX_VALUE))
        );

        I_Hints_pnl.addTab("My Info", I_Info_pnl);

        jLabel1.setText("Subject: ");

        I_Ques_SPane.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Question No.1");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel6.setText("Choices");

        jLabel5.setText("D");

        jLabel4.setText("C");

        jLabel3.setText("B");

        jLabel7.setText("A");

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setText("Question No.4");

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel9.setText("Choices");

        jLabel10.setText("D");

        jLabel11.setText("C");

        jLabel12.setText("B");

        jLabel13.setText("A");

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel14.setText("Question No.3");

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel15.setText("Choices");

        jLabel16.setText("D");

        jLabel17.setText("C");

        jLabel18.setText("B");

        jLabel19.setText("A");

        jLabel20.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel20.setText("Question No.2");

        jLabel21.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel21.setText("Choices");

        jLabel22.setText("D");

        jLabel23.setText("C");

        jLabel24.setText("B");

        jLabel25.setText("A");

        jLabel35.setText("Correct Answer: ");

        I_correct2_cmbo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "A", "B", "C", "D" }));

        jLabel36.setText("Correct Answer: ");

        I_correct3_cmbo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "A", "B", "C", "D" }));

        jLabel37.setText("Correct Answer: ");

        I_correct1_cmbo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "A", "B", "C", "D" }));

        jLabel38.setText("Correct Answer: ");

        I_correct4_cmbo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "A", "B", "C", "D" }));

        javax.swing.GroupLayout I_Ques_pnlLayout = new javax.swing.GroupLayout(I_Ques_pnl);
        I_Ques_pnl.setLayout(I_Ques_pnlLayout);
        I_Ques_pnlLayout.setHorizontalGroup(
            I_Ques_pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(I_Ques_pnlLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(I_Ques_pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(I_Ques_pnlLayout.createSequentialGroup()
                        .addGroup(I_Ques_pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(I_Q4_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 613, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(I_Q3_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 613, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(I_Q2_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 613, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(I_Ques_pnlLayout.createSequentialGroup()
                                .addGroup(I_Ques_pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel13)
                                    .addGroup(I_Ques_pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jLabel10)
                                        .addComponent(jLabel11)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, I_Ques_pnlLayout.createSequentialGroup()
                                            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 6, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(1, 1, 1))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(I_Ques_pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(I_choise41_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 511, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(I_choise43_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 512, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(I_choise44_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 511, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(I_choise42_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 511, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(I_Ques_pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, I_Ques_pnlLayout.createSequentialGroup()
                                    .addGroup(I_Ques_pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jLabel6)
                                        .addGroup(I_Ques_pnlLayout.createSequentialGroup()
                                            .addComponent(jLabel4)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(I_choise3_txt))
                                        .addGroup(I_Ques_pnlLayout.createSequentialGroup()
                                            .addComponent(jLabel3)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(I_choise2_txt))
                                        .addGroup(I_Ques_pnlLayout.createSequentialGroup()
                                            .addComponent(jLabel7)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(I_choise1_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 511, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(I_Ques_pnlLayout.createSequentialGroup()
                                            .addComponent(jLabel5)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(I_choise4_txt)))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel37)
                                    .addGap(18, 18, 18)
                                    .addComponent(I_correct1_cmbo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(I_Q1_txt, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 613, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(132, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, I_Ques_pnlLayout.createSequentialGroup()
                        .addGroup(I_Ques_pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel21)
                            .addGroup(I_Ques_pnlLayout.createSequentialGroup()
                                .addComponent(jLabel23)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(I_choise23_txt))
                            .addGroup(I_Ques_pnlLayout.createSequentialGroup()
                                .addComponent(jLabel24)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(I_choise22_txt))
                            .addGroup(I_Ques_pnlLayout.createSequentialGroup()
                                .addComponent(jLabel25)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(I_choise21_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 511, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(I_Ques_pnlLayout.createSequentialGroup()
                                .addComponent(jLabel22)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(I_choise24_txt)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel35)
                        .addGap(18, 18, 18)
                        .addComponent(I_correct2_cmbo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(116, 116, 116))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, I_Ques_pnlLayout.createSequentialGroup()
                        .addGroup(I_Ques_pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(I_Ques_pnlLayout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel38)
                                .addGap(18, 18, 18)
                                .addComponent(I_correct4_cmbo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(I_Ques_pnlLayout.createSequentialGroup()
                                .addGroup(I_Ques_pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel15)
                                    .addGroup(I_Ques_pnlLayout.createSequentialGroup()
                                        .addComponent(jLabel17)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(I_choise33_txt))
                                    .addGroup(I_Ques_pnlLayout.createSequentialGroup()
                                        .addComponent(jLabel18)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(I_choise32_txt))
                                    .addGroup(I_Ques_pnlLayout.createSequentialGroup()
                                        .addComponent(jLabel19)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(I_choise31_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 511, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(I_Ques_pnlLayout.createSequentialGroup()
                                        .addComponent(jLabel16)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(I_choise34_txt)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                                .addComponent(jLabel36)
                                .addGap(18, 18, 18)
                                .addComponent(I_correct3_cmbo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(118, 118, 118))))
        );
        I_Ques_pnlLayout.setVerticalGroup(
            I_Ques_pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(I_Ques_pnlLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(I_Ques_pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(I_Ques_pnlLayout.createSequentialGroup()
                        .addComponent(I_Q1_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel6))
                    .addGroup(I_Ques_pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(I_correct1_cmbo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel37)))
                .addGap(18, 18, 18)
                .addGroup(I_Ques_pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(I_choise1_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(I_Ques_pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(I_Ques_pnlLayout.createSequentialGroup()
                        .addGroup(I_Ques_pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(I_choise2_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(I_Ques_pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(I_choise3_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel5))
                    .addComponent(I_choise4_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43)
                .addComponent(jLabel20)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(I_Q2_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(I_Ques_pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21)
                    .addComponent(I_correct2_cmbo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel35))
                .addGap(18, 18, 18)
                .addGroup(I_Ques_pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel25)
                    .addComponent(I_choise21_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(I_Ques_pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(I_Ques_pnlLayout.createSequentialGroup()
                        .addGroup(I_Ques_pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel24)
                            .addComponent(I_choise22_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(I_Ques_pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel23)
                            .addComponent(I_choise23_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel22))
                    .addComponent(I_choise24_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(I_Q3_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(I_Ques_pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(I_correct3_cmbo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel36))
                .addGap(18, 18, 18)
                .addGroup(I_Ques_pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(I_choise31_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(I_Ques_pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(I_Ques_pnlLayout.createSequentialGroup()
                        .addGroup(I_Ques_pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel18)
                            .addComponent(I_choise32_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(I_Ques_pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel17)
                            .addComponent(I_choise33_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel16))
                    .addComponent(I_choise34_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(I_Q4_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(I_Ques_pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(I_correct4_cmbo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel38))
                .addGap(18, 18, 18)
                .addGroup(I_Ques_pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(I_choise41_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(I_Ques_pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(I_choise42_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(I_Ques_pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(I_choise43_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(I_Ques_pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(I_choise44_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        I_Ques_SPane.setViewportView(I_Ques_pnl);

        I_submit_btn.setText("Submit Exam");
        I_submit_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                I_submit_btnActionPerformed(evt);
            }
        });

        jLabel28.setText("Duration:");

        I_Duration_cmbo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1 Hour", "2 Hours", "3 Hours", " " }));

        jLabel29.setText("Date:");

        I_day_cmbo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30" }));

        I_month_cmbo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12" }));

        jLabel30.setText("\\ 2019");

        jLabel33.setText("\\");

            jLabel34.setText("Start Time:");

            jLabel41.setText("Exam ID:");

            javax.swing.GroupLayout I_exam_pnlLayout = new javax.swing.GroupLayout(I_exam_pnl);
            I_exam_pnl.setLayout(I_exam_pnlLayout);
            I_exam_pnlLayout.setHorizontalGroup(
                I_exam_pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(I_exam_pnlLayout.createSequentialGroup()
                    .addGroup(I_exam_pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, I_exam_pnlLayout.createSequentialGroup()
                            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(I_submit_btn))
                        .addGroup(I_exam_pnlLayout.createSequentialGroup()
                            .addGap(20, 20, 20)
                            .addGroup(I_exam_pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(I_exam_pnlLayout.createSequentialGroup()
                                    .addComponent(jLabel41)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(I_ExamID_tx)
                                    .addGap(26, 26, 26)
                                    .addComponent(jLabel1)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(I_subject_cmbo, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(jLabel28)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(I_Duration_cmbo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(jLabel29)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(I_day_cmbo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jLabel33, javax.swing.GroupLayout.PREFERRED_SIZE, 9, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(I_month_cmbo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jLabel30)
                                    .addGap(16, 16, 16)
                                    .addComponent(jLabel34)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(I_STime_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(I_Ques_SPane, javax.swing.GroupLayout.DEFAULT_SIZE, 825, Short.MAX_VALUE))))
                    .addContainerGap())
            );
            I_exam_pnlLayout.setVerticalGroup(
                I_exam_pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(I_exam_pnlLayout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(I_exam_pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(I_subject_cmbo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel28)
                        .addComponent(I_Duration_cmbo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel29)
                        .addComponent(I_day_cmbo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(I_month_cmbo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel30)
                        .addComponent(jLabel33)
                        .addComponent(jLabel34)
                        .addComponent(I_STime_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel41)
                        .addComponent(I_ExamID_tx, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(I_Ques_SPane, javax.swing.GroupLayout.DEFAULT_SIZE, 328, Short.MAX_VALUE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(I_submit_btn)
                    .addContainerGap())
            );

            I_Hints_pnl.addTab("Exam preperation ", I_exam_pnl);

            javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
            getContentPane().setLayout(layout);
            layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel27)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(I_LogOut_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(I_Hints_pnl))
                    .addContainerGap())
            );
            layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(I_LogOut_btn)
                        .addComponent(jLabel27))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(I_Hints_pnl, javax.swing.GroupLayout.PREFERRED_SIZE, 438, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap())
            );

            pack();
        }// </editor-fold>//GEN-END:initComponents

    private void I_LogOut_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_I_LogOut_btnActionPerformed
        // TODO add your handling code here:
        LogInOrRegister LOG = new LogInOrRegister();
        this.hide();
        LOG.show();
    }//GEN-LAST:event_I_LogOut_btnActionPerformed

    private void I_showHisto_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_I_showHisto_btnActionPerformed
        // TODO add your handling code here:
        Histo = new Histogram();
        String id = "";
        try {
            id = I_IDs_cmbo.getSelectedItem().toString();
        } catch (NullPointerException e) {
            JOptionPane.showMessageDialog(this, "There's no histogram to show");
        }
        try {
            if (!id.equals("")) {
                GradesAndStudents = Histo.HistoRead(id);
                DefaultCategoryDataset dataset = new DefaultCategoryDataset();

                dataset.addValue(GradesAndStudents.get(0), "#of Students", "0");
                dataset.addValue(GradesAndStudents.get(1), "#of Students", "1");
                dataset.addValue(GradesAndStudents.get(2), "#of Students", "2");
                dataset.addValue(GradesAndStudents.get(3), "#of Students", "3");
                dataset.addValue(GradesAndStudents.get(4), "#of Students", "4");

                JFreeChart chart = ChartFactory.createBarChart("Histogram", "Students", "Grade", dataset, PlotOrientation.VERTICAL, false, true, false);
                CategoryPlot P = chart.getCategoryPlot();
                P.setRangeGridlinePaint(Color.black);
                ChartFrame frame = new ChartFrame("Histogram Window", chart);
                frame.setVisible(true);
                frame.setSize(500, 500);
            }
        } catch (IOException e) {
            System.out.println(e);
        }

        Map<String, Integer> Rank = new HashMap<>();
        ArrayList<String> MostTough = new ArrayList<String>();
        if (!id.equals("")) {
            Rank = i.Ranking(I_IDs_cmbo.getSelectedItem().toString());
            MostTough = i.QuesRanking(Rank);
            jLabel40.setText(MostTough.get(0));
            jLabel42.setText(MostTough.get(1));
            jLabel40.setVisible(true);
            jLabel42.setVisible(true);
            
        }
    }//GEN-LAST:event_I_showHisto_btnActionPerformed

    private void I_submit_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_I_submit_btnActionPerformed
        // TODO add your handling code here:
        if (Exam.checkIDS(I_ExamID_tx.getText()) == false) {
            try {
                Map<String, String> MyMap1 = new HashMap<String, String>();
                MyMap1.put("A", I_choise1_txt.getText());
                MyMap1.put("B", I_choise2_txt.getText());
                MyMap1.put("C", I_choise3_txt.getText());
                MyMap1.put("D", I_choise4_txt.getText());
                Question Q1 = new Question("Q1", I_Q1_txt.getText(), I_correct1_cmbo.getSelectedItem().toString(), MyMap1);

                Map<String, String> MyMap2 = new HashMap<String, String>();
                MyMap2.put("A", I_choise21_txt.getText());
                MyMap2.put("B", I_choise22_txt.getText());
                MyMap2.put("C", I_choise23_txt.getText());
                MyMap2.put("D", I_choise24_txt.getText());
                Question Q2 = new Question("Q2", I_Q2_txt.getText(), I_correct2_cmbo.getSelectedItem().toString(), MyMap2);

                Map<String, String> MyMap3 = new HashMap<String, String>();
                MyMap3.put("A", I_choise31_txt.getText());
                MyMap3.put("B", I_choise32_txt.getText());
                MyMap3.put("C", I_choise33_txt.getText());
                MyMap3.put("D", I_choise34_txt.getText());
                Question Q3 = new Question("Q3", I_Q3_txt.getText(), I_correct3_cmbo.getSelectedItem().toString(), MyMap3);

                Map<String, String> MyMap4 = new HashMap<String, String>();
                MyMap4.put("A", I_choise41_txt.getText());
                MyMap4.put("B", I_choise42_txt.getText());
                MyMap4.put("C", I_choise43_txt.getText());
                MyMap4.put("D", I_choise44_txt.getText());
                Question Q4 = new Question("Q4", I_Q4_txt.getText(), I_correct3_cmbo.getSelectedItem().toString(), MyMap4);

                Question[] Ques = {Q1, Q2, Q3, Q4};

                Exam.FileWrite(String.valueOf(I_ExamID_tx.getText()), false);

                Exam.FileWrite(String.valueOf(I_subject_cmbo.getSelectedItem().toString()), false);

                Exam.FileWrite(String.valueOf(I_Duration_cmbo.getSelectedIndex() + 1), false);

                Exam.FileWrite(I_STime_txt.getText() + ":00", false);

                Exam.FileWrite(String.valueOf(119 + "-" + (I_month_cmbo.getSelectedIndex()) + "-" + (I_day_cmbo.getSelectedIndex() + 1)), true);

                for (int i = 0; i < 4; i++) {
                    Exam.FileWrite(Ques[i].getQnum(), false);
                    Exam.FileWrite(Ques[i].getQcontent(), false);
                    Exam.FileWrite(Ques[i].getListOfChoises().get("A"), false);
                    Exam.FileWrite(Ques[i].getListOfChoises().get("B"), false);
                    Exam.FileWrite(Ques[i].getListOfChoises().get("C"), false);
                    Exam.FileWrite(Ques[i].getListOfChoises().get("D"), false);
                    Exam.FileWrite(Ques[i].getCorrectChoice(), false);
                }
                FileOutputStream outputStream = new FileOutputStream(new File("Ques.txt"), true);

                String Deli = "$";
                byte[] DeliToBytes = Deli.getBytes();
                outputStream.write(DeliToBytes);
                outputStream.flush();
                outputStream.close();

                FileOutputStream out = new FileOutputStream(new File("ExamIDs.txt"), true);
                byte[] strToBytes = I_ExamID_tx.getText().getBytes();
                out.write(strToBytes);
                String delimiter = System.getProperty("line.separator");

                out.write(delimiter.getBytes());
                out.flush();
                out.close();
                I_ExamID_tx.setText(null);
                I_STime_txt.setText(null);
                I_Q1_txt.setText(null);
                I_Q2_txt.setText(null);
                I_Q3_txt.setText(null);
                I_Q4_txt.setText(null);
                I_choise1_txt.setText(null);
                I_choise21_txt.setText(null);
                I_choise22_txt.setText(null);
                I_choise23_txt.setText(null);
                I_choise24_txt.setText(null);
                I_choise2_txt.setText(null);
                I_choise31_txt.setText(null);
                I_choise32_txt.setText(null);
                I_choise33_txt.setText(null);
                I_choise34_txt.setText(null);
                I_choise3_txt.setText(null);
                I_choise41_txt.setText(null);
                I_choise42_txt.setText(null);
                I_choise43_txt.setText(null);
                I_choise44_txt.setText(null);
                I_choise4_txt.setText(null);

            } catch (IOException e) {
                JOptionPane.showMessageDialog(null, "Alert", "Exception Happened!", JOptionPane.ERROR_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(this, "Error", "Exam ID already used try another one!", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_I_submit_btnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(instructor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(instructor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(instructor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(instructor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new instructor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JTextField I_Age_txt;
    private javax.swing.JComboBox I_Duration_cmbo;
    public javax.swing.JTextField I_Email_txt;
    private javax.swing.JPanel I_Eval_pnl;
    private javax.swing.JTextField I_ExamID_tx;
    private javax.swing.JPanel I_GInfo_pnl;
    private javax.swing.JTabbedPane I_Hints_pnl;
    private javax.swing.JComboBox I_IDs_cmbo;
    private javax.swing.JPanel I_Info_pnl;
    private javax.swing.JButton I_LogOut_btn;
    private javax.swing.JTextField I_Q1_txt;
    private javax.swing.JTextField I_Q2_txt;
    private javax.swing.JTextField I_Q3_txt;
    private javax.swing.JTextField I_Q4_txt;
    private javax.swing.JScrollPane I_Ques_SPane;
    private javax.swing.JPanel I_Ques_pnl;
    private javax.swing.JTextField I_STime_txt;
    private javax.swing.JLabel I_address_lbl;
    public javax.swing.JTextField I_address_txt;
    private javax.swing.JTextField I_choise1_txt;
    private javax.swing.JTextField I_choise21_txt;
    private javax.swing.JTextField I_choise22_txt;
    private javax.swing.JTextField I_choise23_txt;
    private javax.swing.JTextField I_choise24_txt;
    private javax.swing.JTextField I_choise2_txt;
    private javax.swing.JTextField I_choise31_txt;
    private javax.swing.JTextField I_choise32_txt;
    private javax.swing.JTextField I_choise33_txt;
    private javax.swing.JTextField I_choise34_txt;
    private javax.swing.JTextField I_choise3_txt;
    private javax.swing.JTextField I_choise41_txt;
    private javax.swing.JTextField I_choise42_txt;
    private javax.swing.JTextField I_choise43_txt;
    private javax.swing.JTextField I_choise44_txt;
    private javax.swing.JTextField I_choise4_txt;
    private javax.swing.JComboBox I_correct1_cmbo;
    private javax.swing.JComboBox I_correct2_cmbo;
    private javax.swing.JComboBox I_correct3_cmbo;
    private javax.swing.JComboBox I_correct4_cmbo;
    private javax.swing.JComboBox I_day_cmbo;
    private javax.swing.JLabel I_email_lbl;
    private javax.swing.JPanel I_exam_pnl;
    private javax.swing.JComboBox I_month_cmbo;
    private javax.swing.JLabel I_name_lbl;
    public javax.swing.JTextField I_name_txt;
    private javax.swing.JLabel I_phone_lbl;
    public javax.swing.JTextField I_phone_txt;
    private javax.swing.JButton I_showHisto_btn;
    private javax.swing.JComboBox I_subject_cmbo;
    private javax.swing.JButton I_submit_btn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel4;
    // End of variables declaration//GEN-END:variables
}
