/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package noMain;

import examinationsystem.*;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author Yatta
 */
public class Studentt extends javax.swing.JFrame {

    /**
     * Creates new form Studentt
     */
    LogInOrRegister L = new LogInOrRegister();
    ArrayList<String> students = null;
    Student s;
    ArrayList<ExamSession> examsessions = null;
    ExamSession ES;
    ArrayList<Exam> Exams = null;

    public Studentt() {
        initComponents();
        S_CurrentExam_pnl.hide();

    }

    public Studentt(Student s) {
        initComponents();
        Exams = new ArrayList<Exam>();
        students = new ArrayList<String>();
        examsessions = new ArrayList<ExamSession>();
        Date now = new java.util.Date();

        ES = new ExamSession();
        this.s = s;
        String[] exams = ExamSession.Spliting();
        if (exams.length > 0) {
            ES = new ExamSession();
            for (int i = 0; i < exams.length; i++) {
                Exams.add(ExamSession.Get_ExamInfo(exams[i]));
                ExamSession S = ES.Assign_Students(Exams.get(i));
                examsessions.add(S);
            }

            for (ExamSession examsession : examsessions) {
                students = examsession.getStud_UserName();
                Date EndDate = new Date(examsession.getCurrentExam().getDate().getYear()
                        , examsession.getCurrentExam().getDate().getMonth(), examsession.getCurrentExam().getDate().getDate()
                        , (examsession.getCurrentExam().getDate().getHours() + examsession.getCurrentExam().getDuration())
                        , examsession.getCurrentExam().getDate().getMinutes(), 0);
                for (String std : students) {
                    if (std.equals(s.getUserName())) {
                        if (!EndDate.before(now)) {
                            ES = examsession;
                            break;
                        } else {
                            ES = null;
                        }
                    }
                }
            }
        }
        S_Name_txt.setText(s.getName());
        S_UserName_txt.setText(s.getUserName());

        S_CurrentExam_pnl.hide();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        S_announ_pnl = new javax.swing.JPanel();
        S_CurrentExam_pnl = new javax.swing.JPanel();
        S_ExamTitle_lbl = new javax.swing.JLabel();
        Start = new javax.swing.JButton();
        S_Duration_lbl = new javax.swing.JLabel();
        S_SDate_lbl = new javax.swing.JLabel();
        Refresh = new javax.swing.JButton();
        S_info_pnl = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        S_Name_txt = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        S_UserName_txt = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        S_LogOut_btn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        S_CurrentExam_pnl.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Current Exam"));

        S_ExamTitle_lbl.setText("Exam Title");

        Start.setText("Start Exam");
        Start.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StartActionPerformed(evt);
            }
        });

        S_Duration_lbl.setText("Duration");

        S_SDate_lbl.setText("Start Date");

        javax.swing.GroupLayout S_CurrentExam_pnlLayout = new javax.swing.GroupLayout(S_CurrentExam_pnl);
        S_CurrentExam_pnl.setLayout(S_CurrentExam_pnlLayout);
        S_CurrentExam_pnlLayout.setHorizontalGroup(
            S_CurrentExam_pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(S_CurrentExam_pnlLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(S_ExamTitle_lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(136, 136, 136)
                .addComponent(S_SDate_lbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(S_Duration_lbl)
                .addGap(97, 97, 97)
                .addComponent(Start)
                .addContainerGap())
        );
        S_CurrentExam_pnlLayout.setVerticalGroup(
            S_CurrentExam_pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(S_CurrentExam_pnlLayout.createSequentialGroup()
                .addGroup(S_CurrentExam_pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Start)
                    .addComponent(S_SDate_lbl)
                    .addComponent(S_Duration_lbl)
                    .addComponent(S_ExamTitle_lbl))
                .addGap(0, 17, Short.MAX_VALUE))
        );

        Refresh.setText("Refresh");
        Refresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RefreshActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout S_announ_pnlLayout = new javax.swing.GroupLayout(S_announ_pnl);
        S_announ_pnl.setLayout(S_announ_pnlLayout);
        S_announ_pnlLayout.setHorizontalGroup(
            S_announ_pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(S_announ_pnlLayout.createSequentialGroup()
                .addContainerGap(785, Short.MAX_VALUE)
                .addComponent(Refresh)
                .addContainerGap())
            .addComponent(S_CurrentExam_pnl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        S_announ_pnlLayout.setVerticalGroup(
            S_announ_pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(S_announ_pnlLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(S_CurrentExam_pnl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 274, Short.MAX_VALUE)
                .addComponent(Refresh)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Announcements", S_announ_pnl);

        S_info_pnl.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel7.setText("Name:");

        jLabel3.setText("UserName:");

        javax.swing.GroupLayout S_info_pnlLayout = new javax.swing.GroupLayout(S_info_pnl);
        S_info_pnl.setLayout(S_info_pnlLayout);
        S_info_pnlLayout.setHorizontalGroup(
            S_info_pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(S_info_pnlLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(S_Name_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(171, 171, 171)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(S_UserName_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        S_info_pnlLayout.setVerticalGroup(
            S_info_pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(S_info_pnlLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(S_info_pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(S_Name_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(S_UserName_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Welcome");

        S_LogOut_btn.setText("Log Out");
        S_LogOut_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                S_LogOut_btnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTabbedPane1)
                    .addComponent(S_info_pnl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(S_LogOut_btn)
                        .addGap(10, 10, 10)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(S_LogOut_btn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                .addComponent(S_info_pnl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 417, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void StartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StartActionPerformed
        // TODO add your handling code here:
        Date late = new Date(119, ES.getCurrentExam().getDate().getMonth(), ES.getCurrentExam().getDate().getDate(),
                ES.getCurrentExam().getDate().getHours(), ES.getCurrentExam().getDate().getMinutes() + 30, 00);

        Date now = new java.util.Date();

        SimpleDateFormat formatter = new SimpleDateFormat("HH:mm:ss");
        formatter.format(now);

        if (now.before(ES.getCurrentExam().getDate())) {
            JOptionPane.showMessageDialog(jTabbedPane1, "Exam hasn't started yet", "Error", JOptionPane.ERROR_MESSAGE);
        } else if (now.after(ES.getCurrentExam().getDate()) || now.equals(ES.getCurrentExam().getDate())) {
            if (now.before(late)) {
                LogInOrRegister.check = false;
                CurrentExam C = new CurrentExam(ES);
                C.show();
                S_CurrentExam_pnl.hide();
            } else if (now.after(late)) {
                JOptionPane.showMessageDialog(jTabbedPane1, "Access Denied", "Error", JOptionPane.ERROR_MESSAGE);
            }
        }

    }//GEN-LAST:event_StartActionPerformed

    private void RefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RefreshActionPerformed
        // TODO add your handling code here:
        if (ES != (null)) {
            if (LogInOrRegister.check == true) {
                S_ExamTitle_lbl.setText(ES.getCurrentExam().getCourseID() + " Exam");
                S_SDate_lbl.setText("Start Date:" + ES.getCurrentExam().getDate());
                S_Duration_lbl.setText("Duration: " + ES.getCurrentExam().getDuration() + " Hour(s)");
                S_CurrentExam_pnl.show();
            }
        } else {
            JOptionPane.showMessageDialog(jTabbedPane1, "No new Exams", "INFO", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_RefreshActionPerformed

    private void S_LogOut_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_S_LogOut_btnActionPerformed
        // TODO add your handling code here:
        LogInOrRegister LOG = new LogInOrRegister();
        this.hide();
        LOG.show();
    }//GEN-LAST:event_S_LogOut_btnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Studentt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Studentt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Studentt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Studentt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Studentt().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Refresh;
    private javax.swing.JPanel S_CurrentExam_pnl;
    private javax.swing.JLabel S_Duration_lbl;
    private javax.swing.JLabel S_ExamTitle_lbl;
    private javax.swing.JButton S_LogOut_btn;
    public javax.swing.JTextField S_Name_txt;
    private javax.swing.JLabel S_SDate_lbl;
    public javax.swing.JTextField S_UserName_txt;
    private javax.swing.JPanel S_announ_pnl;
    private javax.swing.JPanel S_info_pnl;
    private javax.swing.JButton Start;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTabbedPane jTabbedPane1;
    // End of variables declaration//GEN-END:variables
}
